# Generated by Django 3.0.3 on 2020-11-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('DOCTOR', 'Doctor'), ('PATIENT', 'Patient')], default='PATIENT', max_length=50, verbose_name='Type'),
        ),
    ]
