# Generated by Django 3.0.3 on 2020-11-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='is admin'),
        ),
    ]
