# Generated by Django 3.0.3 on 2021-07-05 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SensorType1', models.CharField(blank=True, max_length=25, null=True)),
                ('HeartRate', models.CharField(blank=True, max_length=5, null=True)),
                ('SensorType2', models.CharField(blank=True, max_length=25, null=True)),
                ('SpO2', models.CharField(blank=True, max_length=5, null=True)),
                ('Time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sensor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
